name: "Get all changed files"
description: ""
inputs:
  environment:
    required: true
    description: "Target environment" 
  file-filter:
    required: true
    description: "Filter to limit what files are returned"
outputs:
  added_files:
    value: ${{ steps.check_files.outputs.added_files}}
  modified_files:
    value: ${{ steps.check_files.outputs.modified_files}}
  renamed_files:
    value: ${{ steps.check_files.outputs.renamed_files}}
  all_changed_files:
    value: ${{ steps.check_files.outputs.all_changed_files}}
runs: 
  using: "composite"
  steps:
    - name: Get diff
      shell: bash
      run: |
        base=$([ "${{ inputs.environment }}" == "dev" ] &&  echo "${{ github.event.pull_request.base.sha }}" || echo "${{ github.event.before }}")
        head=$([ "${{ inputs.environment }}" == "dev" ] &&  echo "${{ github.event.pull_request.head.sha }}" || echo "${{ github.event.after }}")
        file_type_filter=$([ -z "${{ inputs.file-filter }}" ] &&   echo "" || echo ' -- "${{ inputs.file-filter }}"')

        ADDED_FILES=$(git diff --name-only --diff-filter=A $base $head $file_type_filter| paste -sd "," -)
        MODIFIED_FILES=$(git diff --name-only --diff-filter=M $base $head $file_type_filter | paste -sd "," -)
        RENAMED_FILES=$(git diff --name-status --diff-filter=R $base $head $file_type_filter | awk '{print $2 ">" $3}' | paste -sd "," -)
        
        {
          echo "added_files=$ADDED_FILES"
          echo "modified_files=$MODIFIED_FILES"
          echo "renamed_files=$RENAMED_FILES"
          echo "all_changed_files+=($ADDED_FILES $MODIFIED_FILES $RENAMED_FILES)"
        } >> "$GITHUB_OUTPUT"