name: Get Changed Files

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      file-type:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get all changed files
        id: check_files
        run: |
          base=$([ "${{ inputs.environment }}" == "dev" ] &&  echo "${{ github.event.pull_request.base.sha }}" || echo "${{ github.event.before }}")
          head=$([ "${{ inputs.environment }}" == "dev" ] &&  echo "${{ github.event.pull_request.head.sha }}" || echo "${{ github.event.after }}")

          if [[ -v "{{ inputs.file-type }}"]]; then
            file_type_filter=' -- "*.${{ inputs.file-type }}"'
          else
            file_type_filter=""
          fi"

          ADDED_FILES=$(git diff --name-only --diff-filter=A $base $head $file_type_filter| paste -sd "," -)
          MODIFIED_FILES=$(git diff --name-only --diff-filter=M $base $head  $file_type_filter | paste -sd "," -)
          RENAMED_FILES=$(git diff --name-status --diff-filter=R $base $head  $file_type_filter | awk '{print $2 ">" $3}' | paste -sd "," -)
          
          {
            echo "added_files=$ADDED_FILES"
            echo "modified_files=$MODIFIED_FILES"
            echo "renamed_files=$RENAMED_FILES"
          } >> "$GITHUB_OUTPUT"